.Dd MONTH DAY, YEAR
.Dt LIBRARY_NAME_UPPERCASE 3
.Os
.Sh NAME
.Nm LIBRARY_NAME
.Nd ONE_LINE_DESCRIPTION
.Sh SYNOPSIS
.Em import LIBRARY_NAME
.Pp
.Ft TYPE_Boolean_Character_Integer_Float_String_List
.Fo LIBRARY_NAME.FUNCTION_NAME
.Fa "TYPE ARGUMENT"
.Fa "TYPE ARGUMENT"
.Fc
.Ft TYPE
.Fo LIBRARY_NAME.FUNCTION_NAME
.Fa "TYPE ARGUMENT"
.Fc
.Sh DESCRIPTION
The
.Fn FUNCTION_NAME
function returns XXX if
.Fa ARGUMENT
is SOME_CONDITION or SOMETHING_ELSE if not.
.Sh ENVIRONMENT
The
.Ev LIBRARY_DEBUG
environment variable can be set to any value to enable debug mode.
.Sh SEE ALSO
.Xr COMMAND 1 ,
.Xr LIBRARY 3
.Sh STANDARDS
The
.Lb LIBRARY_NAME
tries to follow the PEP 8 style guide for Python code.
.Sh HISTORY
This library was made for the
.Lk https://github.com/HubTou/PNU PNU project
.Sh LICENSE
This library is available under the 3\-clause BSD license.
.Sh AUTHORS
.An AUTHOR_NAME
.Sh CAVEATS
.Sh SECURITY CONSIDERATIONS
