.TH ABOUT 1
.SH NAME
about \- show system information
.SH SYNOPSIS
.B about
[\-a|\-\-all]
[\-S|\-\-sys|\-\-system]
[\-H|\-\-hw|\-\-hardware]
[\-O|\-\-os|\-\-operating]
[\-E|\-\-env|\-\-environment]
[\-P|\-\-py|\-\-python]
[\-d|\-\-debug]
[\-h|\-\-help|\-?]
[\-v|\-\-version]
[\-\-]
.SH DESCRIPTION
The
.B about
utility shows most of the system information available through the Python Standard Library.
.SH OPTIONS
.TP
.BR \-a|\-\-all
Same as -SHOEP.
.TP
.BR \-S|\-\-sys|\-\-system
Show information about the system.
.TP
.BR \-H|\-\-hw|\-\-hardware
Show information about the hardware.
.TP
.BR \-O|\-\-os|\-\-operating
Show information about the Operating System.
.TP
.BR \-E|\-\-env|\-\-environment
Show information about the environment.
.TP
.BR \-P|\-\-py|\-\-python
Show information about Python.
.TP
.BR \-d|\-\-debug
Enable debug level messages.
.TP
.BR \-h|\-\-help|\-?
Print usage and a short help message and exit.
.TP
.BR \-v|\-\-version
Print version and exit.
.TP
.BR \-\-
Options processing terminator.
.SH EXIT STATUS
The about utility exits 0 on success, and >0 if an error occurs.
.SH SEE ALSO
uname(1), sysctl(8)
.PP
https://docs.python.org/3/library/index.html
.SH STANDARDS
The about command is not a standard UNIX/POSIX command.
.PP
It tries to follow the PEP 8 style guide for Python code (see https://www.python.org/dev/peps/pep-0008/).
We check this with the Pylint command (see https://www.pylint.org/).
.SH PORTABILITY
Tested OK under Windows.
.SH HISTORY
The about command was created as an example for the PNU / PyNIX project, testing many of the standard Python functions for getting system information.
.SH LICENSE
This utility is available under the 3-clause BSD license (see https://opensource.org/licenses/BSD-3-Clause).
.SH AUTHOR
Hubert Tournier
